title: Invest With Maries 
email: rmaries@gmail.com
description: >-
   Professional Mutual Fund Distribution and Financial Advisory Services. 
   Helping you grow your wealth with discipline
baseurl: "/InvestWithMaries" # the subpath of your site, e.g. /blog
url: "https://rmaries.github.io" # the base hostname & protocol for your site
github_username: rmaries
linkedin_url: https://www.linkedin.com/in/marieswaranr/

# Build settings
theme: jekyll-theme-minimal # Using a basic theme as a starting point, we'll customize
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Pagination for blog
paginate: 5
paginate_path: "/blog/page:num/"

# Permalinks
permalink: /:categories/:title/
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:title/
